# Generated by Django 2.0.1 on 2018-01-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(upload_to='data_files/csv')),
                ('test_fields', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('stock', models.IntegerField(default=0)),
                ('available', models.NullBooleanField(default=False)),
                ('catagory', models.CharField(default='', max_length=200)),
                ('productID', models.CharField(max_length=220)),
            ],
        ),
    ]
