<<<<<<< HEAD
# Generated by Django 2.0.1 on 2018-02-20 06:53
=======
# Generated by Django 2.0.1 on 2018-01-30 18:22
>>>>>>> bc65a24b008b8b8463de5502abfcdf87bb321000

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='FacebookData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=500)),
                ('comment', models.CharField(max_length=500)),
                ('comment_from', models.CharField(max_length=500)),
                ('number_of_likes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> bc65a24b008b8b8463de5502abfcdf87bb321000
            name='FileDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('path', models.FileField(upload_to='data_files/csv')),
<<<<<<< HEAD
=======
                ('test_fields', models.IntegerField(default=0)),
>>>>>>> bc65a24b008b8b8463de5502abfcdf87bb321000
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(default='')),
                ('stock', models.IntegerField(default=0)),
                ('available', models.NullBooleanField(default=False)),
                ('catagory', models.CharField(default='', max_length=200)),
<<<<<<< HEAD
            ],
        ),
        migrations.CreateModel(
            name='TwitterData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_id', models.BigIntegerField(default=0, null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('number_of_likes', models.IntegerField(default=0, null=True)),
                ('posted_by', models.CharField(max_length=30, null=True)),
                ('replied_to', models.CharField(max_length=30, null=True)),
                ('replied_to_status_id', models.CharField(max_length=30, null=True)),
=======
                ('productID', models.CharField(max_length=220)),
>>>>>>> bc65a24b008b8b8463de5502abfcdf87bb321000
            ],
        ),
    ]
