# Generated by Django 2.0.1 on 2018-02-20 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdata',
            name='replied_to_status_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
