# Generated by Django 2.0.1 on 2018-02-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0002_product_barcode_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barode_id',
            field=models.IntegerField(default=0),
        ),
    ]
