# Generated by Django 2.0.1 on 2018-02-20 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0002_auto_20180220_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterdata',
            name='replied_to_status_id',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
