# Generated by Django 2.0.1 on 2018-02-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0003_product_barode_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('path', models.ImageField(upload_to='data_files/csv')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='barode_id',
            field=models.CharField(max_length=220),
        ),
    ]
