# Generated by Django 2.0.1 on 2018-02-20 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0003_auto_20180220_0705'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterdata',
            old_name='replied_to_status_id',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='twitterdata',
            old_name='posted_by',
            new_name='posted_by_user',
        ),
        migrations.RenameField(
            model_name='twitterdata',
            old_name='status',
            new_name='replied_to_message_id',
        ),
        migrations.RenameField(
            model_name='twitterdata',
            old_name='replied_to',
            new_name='replied_to_user',
        ),
        migrations.RemoveField(
            model_name='twitterdata',
            name='status_id',
        ),
        migrations.AddField(
            model_name='twitterdata',
            name='message_id',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
