# Generated by Django 2.0.1 on 2018-01-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0003_auto_20180126_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catagory',
            field=models.CharField(default='', max_length=200),
        ),
    ]
