# Generated by Django 2.0.1 on 2018-01-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0004_product_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.NullBooleanField(default=False),
        ),
    ]
