# Generated by Django 2.0.1 on 2018-02-20 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0004_auto_20180220_0738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='twitterdata',
            old_name='message_id',
            new_name='id_message',
        ),
    ]
