# Generated by Django 2.0.1 on 2018-01-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_site', '0006_filedatamodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedatamodel',
            name='name',
        ),
        migrations.AlterField(
            model_name='filedatamodel',
            name='path',
            field=models.FileField(upload_to='static/csv'),
        ),
    ]
